title: George Conner

tagline: Software engineer and developer

url: "http://www.georgeconner.com"

remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme 
  - jekyll-feed
  - jekyll-seo-tag